// Enhanced farmers data with Indian names
export const farmers = [
  {
    id: 1,
    name: "Rajesh Kumar",
    produce: "Organic Tomatoes",
    location: "Punjab",
    rating: 4.8,
    trust: 95,
    email: "rajesh@farmsindia.com",
    phone: "+91-98765-43210",
    totalContracts: 15,
    activeContracts: 3,
    verified: true,
  },
  {
    id: 2,
    name: "Priya Sharma",
    produce: "Fresh Wheat",
    location: "Haryana",
    rating: 4.9,
    trust: 98,
    email: "priya@sharmafarms.com",
    phone: "+91-98765-43211",
    totalContracts: 22,
    activeContracts: 5,
    verified: true,
  },
  {
    id: 3,
    name: "Amit Patel",
    produce: "Cotton & Groundnut",
    location: "Gujarat",
    rating: 4.7,
    trust: 92,
    email: "amit@patelkrushi.com",
    phone: "+91-98765-43212",
    totalContracts: 18,
    activeContracts: 2,
    verified: true,
  },
  {
    id: 4,
    name: "Lakshmi Reddy",
    produce: "Organic Rice",
    location: "Telangana",
    rating: 4.6,
    trust: 89,
    email: "lakshmi@reddyorganics.com",
    phone: "+91-98765-43213",
    totalContracts: 12,
    activeContracts: 4,
    verified: false,
  },
  {
    id: 5,
    name: "Suresh Singh",
    produce: "Sugarcane",
    location: "Uttar Pradesh",
    rating: 4.8,
    trust: 94,
    email: "suresh@singhfarms.com",
    phone: "+91-98765-43214",
    totalContracts: 25,
    activeContracts: 6,
    verified: true,
  },
  {
    id: 6,
    name: "Anjali Desai",
    produce: "Vegetables & Spices",
    location: "Maharashtra",
    rating: 4.9,
    trust: 97,
    email: "anjali@desaikrushi.com",
    phone: "+91-98765-43215",
    totalContracts: 20,
    activeContracts: 3,
    verified: true,
  },
];

// Smart contracts data with blockchain integration
export const contracts = [
  {
    id: "CNT-001",
    farmer: "Rajesh Kumar",
    farmerId: 1,
    produce: "Organic Tomatoes",
    quantity: "500 kg",
    pricePerUnit: 2.5,
    totalValue: 1250,
    status: "Active",
    delivery: "2024-01-15",
    createdDate: "2023-12-01",
    blockchainHash: "0x1a2b3c4d5e6f789a",
  },
  {
    id: "CNT-002",
    farmer: "Priya Sharma",
    farmerId: 2,
    produce: "Fresh Lettuce",
    quantity: "300 kg",
    pricePerUnit: 3.0,
    totalValue: 900,
    status: "Pending",
    delivery: "2024-01-20",
    createdDate: "2023-12-05",
    blockchainHash: "0x2b3c4d5e6f7g8h9i",
  },
  {
    id: "CNT-003",
    farmer: "David Chen",
    farmerId: 3,
    produce: "Sweet Corn",
    quantity: "1000 kg",
    pricePerUnit: 2.0,
    totalValue: 2000,
    status: "Active",
    delivery: "2024-01-25",
    createdDate: "2023-12-03",
    blockchainHash: "0x3c4d5e6f7g8h9i0j",
  },
  {
    id: "CNT-004",
    farmer: "Sarah Johnson",
    farmerId: 4,
    produce: "Organic Carrots",
    quantity: "400 kg",
    pricePerUnit: 1.8,
    totalValue: 720,
    status: "Completed",
    delivery: "2024-01-10",
    createdDate: "2023-11-28",
    blockchainHash: "0x4d5e6f7g8h9i0j1k",
  },
];

// Blockchain transaction records
export const transactions = [
  {
    id: "TXN-001",
    farmer: "John Smith",
    farmerId: 1,
    lot: "LOT-2024-001",
    date: "2024-01-10",
    amount: 1250.0,
    status: "Confirmed",
    hash: "0x1a2b3c4d5e6f789a12b3c4d5e6f7g8h9",
    contractId: "CNT-001",
    type: "Payment",
  },
  {
    id: "TXN-002",
    farmer: "Maria Garcia",
    farmerId: 2,
    lot: "LOT-2024-002",
    date: "2024-01-09",
    amount: 900.0,
    status: "Pending",
    hash: "0x2b3c4d5e6f7g8h9i23c4d5e6f7g8h9i0",
    contractId: "CNT-002",
    type: "Payment",
  },
  {
    id: "TXN-003",
    farmer: "David Chen",
    farmerId: 3,
    lot: "LOT-2024-003",
    date: "2024-01-08",
    amount: 2000.0,
    status: "Confirmed",
    hash: "0x3c4d5e6f7g8h9i0j34d5e6f7g8h9i0j1",
    contractId: "CNT-003",
    type: "Payment",
  },
  {
    id: "TXN-004",
    farmer: "Sarah Johnson",
    farmerId: 4,
    lot: "LOT-2024-004",
    date: "2024-01-07",
    amount: 720.0,
    status: "Confirmed",
    hash: "0x4d5e6f7g8h9i0j1k45e6f7g8h9i0j1k2",
    contractId: "CNT-004",
    type: "Payment",
  },
  {
    id: "TXN-005",
    farmer: "Mike Wilson",
    farmerId: 5,
    lot: "LOT-2024-005",
    date: "2024-01-06",
    amount: 1500.0,
    status: "Failed",
    hash: "0x5e6f7g8h9i0j1k2l56f7g8h9i0j1k2l3",
    contractId: "CNT-005",
    type: "Payment",
  },
];

// Recent activity feed (use translation keys)
export const activities = [
  {
    id: 1,
    actionKey: "retailer.dashboard.activity.actions.newContract",
    farmer: "John Smith",
    timeKey: "retailer.dashboard.time.ago.hours",
    timeCount: 2,
    type: "contract",
    detailsKey: "retailer.dashboard.activity.details.contract",
    detailsParams: { contractId: "CNT-001", produce: "Organic Tomatoes", amount: "$1,250" },
  },
  {
    id: 2,
    actionKey: "retailer.dashboard.activity.actions.paymentProcessed",
    farmer: "Maria Garcia",
    timeKey: "retailer.dashboard.time.ago.hours",
    timeCount: 4,
    type: "payment",
    detailsKey: "retailer.dashboard.activity.details.payment",
    detailsParams: { amount: "$900" },
  },
  {
    id: 3,
    actionKey: "retailer.dashboard.activity.actions.lotVerified",
    farmer: "David Chen",
    timeKey: "retailer.dashboard.time.ago.hours",
    timeCount: 6,
    type: "verification",
    detailsKey: "retailer.dashboard.activity.details.lotVerified",
    detailsParams: { lotId: "LOT-2024-003" },
  },
  {
    id: 4,
    actionKey: "retailer.dashboard.activity.actions.qualityCheckCompleted",
    farmer: "Sarah Johnson",
    timeKey: "retailer.dashboard.time.ago.hours",
    timeCount: 8,
    type: "quality",
    detailsKey: "retailer.dashboard.activity.details.qualityCheck",
    detailsParams: { produce: "Organic Carrots" },
  },
  {
    id: 5,
    actionKey: "retailer.dashboard.activity.actions.deliveryScheduled",
    farmer: "Mike Wilson",
    timeKey: "retailer.dashboard.time.ago.days",
    timeCount: 1,
    type: "delivery",
    detailsKey: "retailer.dashboard.activity.details.deliveryScheduled",
    detailsParams: { produce: "Bell Peppers", date: "Jan 15, 2024" },
  },
];

// KPI dashboard data (period uses translation key)
export const kpiData = {
  connectedFarmers: {
    value: 247,
    change: "+12%",
    period: "retailer.dashboard.kpi.period.lastMonth",
    icon: "Users",
    trend: "up",
  },
  activeContracts: {
    value: 89,
    change: "+5%",
    period: "retailer.dashboard.kpi.period.lastMonth",
    icon: "FileText",
    trend: "up",
  },
  pendingPayments: {
    value: "$24,580",
    change: "3 payments due",
    period: "",
    icon: "CreditCard",
    trend: "neutral",
  },
  lotsVerified: {
    value: 1234,
    change: "+18%",
    period: "retailer.dashboard.kpi.period.lastMonth",
    icon: "CheckCircle",
    trend: "up",
  },
};

// Supply chain tracking data
export const supplyChainTimeline = [
  {
    stage: "Farm",
    location: "Smith Farm, CA",
    date: "2024-01-01",
    status: "completed",
    details: "Harvested and packaged",
    temperature: "4°C",
    humidity: "85%",
  },
  {
    stage: "Distributor",
    location: "FreshCorp Warehouse",
    date: "2024-01-05",
    status: "completed",
    details: "Quality checked and stored",
    temperature: "2°C",
    humidity: "80%",
  },
  {
    stage: "Retailer",
    location: "Your Store",
    date: "2024-01-08",
    status: "current",
    details: "Received and stocked",
    temperature: "3°C",
    humidity: "75%",
  },
  {
    stage: "Consumer",
    location: "End Customer",
    date: "Pending",
    status: "pending",
    details: "Awaiting purchase",
    temperature: "-",
    humidity: "-",
  },
];

// Retailer profile information
export const retailerProfile = {
  organizationName: "RetailCorp Inc.",
  contactPerson: "John Manager",
  email: "john@retailcorp.com",
  phone: "+1 (555) 123-4567",
  businessAddress: "123 Commerce St, Business City, BC 12345",
  type: "Premium Grocery Chain",
  status: "Verified Retailer",
  licenseNumber: "RET-2024-001",
  establishedYear: "2015",
  employeeCount: "150-200",
};

// Filter and dropdown options (labels are translation keys)
export const filterOptions = {
  produceTypes: [
    { value: "all", label: "filter.produce.all" },
    { value: "vegetables", label: "filter.produce.vegetables" },
    { value: "fruits", label: "filter.produce.fruits" },
    { value: "grains", label: "filter.produce.grains" },
    { value: "organic", label: "filter.produce.organic" },
  ],
  locations: [
    { value: "all", label: "filter.locations.all" },
    { value: "california", label: "filter.locations.california" },
    { value: "texas", label: "filter.locations.texas" },
    { value: "florida", label: "filter.locations.florida" },
    { value: "iowa", label: "filter.locations.iowa" },
    { value: "oregon", label: "filter.locations.oregon" },
  ],
  units: [
    { value: "kg", label: "filter.units.kilograms" },
    { value: "lbs", label: "filter.units.pounds" },
    { value: "tons", label: "filter.units.tons" },
    { value: "boxes", label: "filter.units.boxes" },
  ],
  languages: [
    { value: "en", label: "EN" },
    { value: "es", label: "ES" },
    { value: "fr", label: "FR" },
    { value: "hi", label: "HI" },
  ],
};

export const navItems = [
  { id: "browse", label: "Browse Products", icon: "Package" },
  { id: "analytics", label: "Analytics", icon: "BarChart3" },
  { id: "network", label: "Network", icon: "Users" },
  { id: "contracts", label: "Contracts", icon: "FileText" },
  { id: "qr", label: "QR Scanner", icon: "QrCode" },
];

// Chart data for dashboard analytics
export const chartPlaceholderData = {
  monthlyTransactions: {
    title: "Monthly Transactions",
    icon: "TrendingUp",
    data: [
      { month: "Jan", value: 45000 },
      { month: "Feb", value: 52000 },
      { month: "Mar", value: 48000 },
      { month: "Apr", value: 61000 },
      { month: "May", value: 55000 },
      { month: "Jun", value: 67000 },
    ],
  },
  produceCategories: {
    title: "Produce Categories",
    icon: "BarChart3",
    data: [
      { category: "Vegetables", value: 45 },
      { category: "Fruits", value: 30 },
      { category: "Grains", value: 15 },
      { category: "Organic", value: 10 },
    ],
  },
};

// Mock scanned products for QR functionality
